### ISSUE TITLE
Type error regarding React.Component in 05-generics/40

### ISSUE THREAD

**Issue by kimroen** [total-typescript/react-typescript-tutorial#10]
In [this challenge](https://www.totaltypescript.com/workshops/advanced-react-with-typescript/using-generics-with-components/generics-in-class-components/exercise): `src/05-generics/40-generic-class-components.problem.tsx`

During and after solving the challenge, this TypeScript error persists:

```
src/05-generics/40-generic-class-components.problem.tsx:9:28 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

9 export class Table extends React.Component<TableProps> {
                             ~~~~~
```

Importing `React` resolves this issue, but this seems both unnecessary as we'll learn later in the course, and not related to what we're trying to communicate here.

**Comment by mattpocock** [comment]
Fixed - the React import is required here because it's referenced at runtime, not compile time.
