### ISSUE TITLE
SOLUTION=true in package.json not working for Windows

### ISSUE THREAD

**Issue by isimmons** [total-typescript/react-typescript-tutorial#3]
On Windows you can't set the environment variable this way or it tries to run a program called "SOLUTION"

```
"solution": "SOLUTION=true node scripts/exercise.js",
```

A quick search and I found this cross platform [fix](https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json). I don't have a Mac or Linux to test it on but it makes sense to me that this way lets npm set the environment variable for us. It is working for me on Windows.

```
"solution": "env SOLUTION=true node scripts/exercise.js",
```

I would have done a PR but I'm not even sure is this the correct way.

**Comment by mattpocock** [comment]
Fixed, thanks!
